export const gifts = [
  "Flame",
  "Water",
  "Frost",
  "Lightning",
  "Wind",
  "Earth",
  "Metal",
  "Plants",
  "Sand",
  "Lava",
  "Smoke",
  "Mist",
  "Crystal",
  "Glass",
  "Blood",
  "Bone",
  "Gravity",
  "Magnetism",
  "Sound",
  "Light",
  "Shadow",
  "Weather",
  "Storm",
  "Heat",
  "Cold",
  "Poison",
  "Acid",
  "Lightning Absorption",
  "Flame Absorption",
  "Water Breathing",
  "Teleportation",
  "Portals",
  "Flight",
  "Superspeed",
  "Titan Strength",
  "Endurance",
  "Stone Skin",
  "Steel Skin",
  "Elasticity",
  "Gigantification",
  "Shrinking",
  "Shapeshifting",
  "Beast Form",
  "Dragon Form",
  "Ghost Form",
  "Smoke Form",
  "Water Form",
  "Fire Form",
  "Ice Form",
  "Lightning Form",
  "Invisibility",
  "Intangibility",
  "Regeneration",
  "Healing",
  "Resurrection",
  "Poison Touch",
  "Paralysis Touch",
  "Sleep Touch",
  "Explosion",
  "Shockwave",
  "Energy Blast",
  "Laser Vision",
  "Heat Vision",
  "Cold Breath",
  "Fire Breath",
  "Lightning Breath",
  "Force Fields",
  "Energy Weapons",
  "Weapon Summoning",
  "Cloning",
  "Illusions",
  "Mind Reading",
  "Mind Control",
  "Memory Reading",
  "Future Sight",
  "Spirit Sight",
  "X-Ray Vision",
  "Enhanced Senses",
  "Danger Sense",
  "Perfect Aim",
  "Genius",
  "Machine Command",
  "Animal Speech",
  "Plant Growth",
  "Monster Taming",
  "Power Copying",
  "Power Nullification",
  "Energy Absorption",
  "Kinetic Storage",
  "Damage Reflection",
  "Luck",
  "Dream Walking",
  "Astral Projection",
  "Curse Casting",
  "Barriers",
  "Threads",
  "Paper",
  "Ink",
  "Time Stop",
  "Custom",
] as const;

export type Gift = (typeof gifts)[number];

export const giftDescriptions = {
  Flame: "Create and shape fire at will.",
  Water: "Move and shape nearby water.",
  Frost: "Freeze matter and summon biting cold.",
  Lightning: "Generate and direct electrical currents.",
  Wind: "Command air currents and cutting gusts.",
  Earth: "Shape stone, soil, and solid ground.",
  Metal: "Bend and reshape metal without touching it.",
  Plants: "Command existing plant life.",
  Sand: "Move sand in waves, blades, and shields.",
  Lava: "Create and guide molten rock.",
  Smoke: "Produce and control clouds of smoke.",
  Mist: "Call forth and shape concealing mist.",
  Crystal: "Grow durable crystal into useful forms.",
  Glass: "Shape glass into razor-sharp constructs.",
  Blood: "Manipulate blood once it leaves the body.",
  Bone: "Grow and reshape your own bones.",
  Gravity: "Increase, reduce, or redirect gravity nearby.",
  Magnetism: "Attract, repel, and sense magnetic metal.",
  Sound: "Shape vibrations into silence or force.",
  Light: "Bend light into flashes and focused beams.",
  Shadow: "Stretch and solidify nearby shadows.",
  Weather: "Gradually alter the weather around you.",
  Storm: "Summon violent wind, rain, and lightning.",
  Heat: "Raise the temperature of anything nearby.",
  Cold: "Drain heat from objects and surroundings.",
  Poison: "Create and alter natural toxins.",
  Acid: "Produce a liquid that dissolves most materials.",
  "Lightning Absorption": "Absorb electricity and release it later.",
  "Flame Absorption": "Absorb existing flames and release them through fire-infused attacks. You cannot create fire of your own.",
  "Water Breathing": "Breathe and speak freely beneath water.",
  Teleportation: "Instantly move to a place you can see.",
  Portals: "Open paired doorways between two places.",
  Flight: "Move freely through the air.",
  Superspeed: "Move and react at impossible speed.",
  "Titan Strength": "Possess strength far beyond human limits.",
  Endurance: "Withstand extreme strain, pain, and exhaustion.",
  "Stone Skin": "Harden your skin into protective stone.",
  "Steel Skin": "Turn your skin into nearly unbreakable steel.",
  Elasticity: "Stretch and bend your body without harm.",
  Gigantification: "Grow to a towering size and strength.",
  Shrinking: "Reduce yourself to a tiny size.",
  Shapeshifting: "Alter your face, voice, and body.",
  "Beast Form": "Transform into a powerful feral creature.",
  "Dragon Form": "Take the form of a mighty dragon.",
  "Ghost Form": "Become weightless, silent, and spectral.",
  "Smoke Form": "Dissolve your body into living smoke.",
  "Water Form": "Turn your body into flowing water.",
  "Fire Form": "Become a body of living flame.",
  "Ice Form": "Become solid, resilient living ice.",
  "Lightning Form": "Become a flash of living electricity.",
  Invisibility: "Hide yourself completely from normal sight.",
  Intangibility: "Pass safely through solid matter.",
  Regeneration: "Rapidly repair damage to your own body.",
  Healing: "Close wounds and restore another person's body.",
  Resurrection: "Return the recently dead to life.",
  "Poison Touch": "Inflict a weakening toxin through touch.",
  "Paralysis Touch": "Temporarily stop movement through touch.",
  "Sleep Touch": "Put a living target into deep sleep.",
  Explosion: "Create a violent blast from a chosen point.",
  Shockwave: "Release a burst of concussive force.",
  "Energy Blast": "Fire concentrated bolts of raw energy.",
  "Laser Vision": "Project precise cutting beams from your eyes.",
  "Heat Vision": "Project intense heat wherever you look.",
  "Cold Breath": "Exhale a freezing wind.",
  "Fire Breath": "Breathe a sweeping stream of flame.",
  "Lightning Breath": "Exhale a branching surge of electricity.",
  "Force Fields": "Create invisible shields of solid force.",
  "Energy Weapons": "Forge temporary weapons from pure energy.",
  "Weapon Summoning": "Call a chosen weapon into your hand.",
  Cloning: "Create temporary copies of yourself.",
  Illusions: "Create convincing sights, sounds, and sensations.",
  "Mind Reading": "Hear the surface thoughts of nearby minds.",
  "Mind Control": "Briefly impose a command on another mind.",
  "Memory Reading": "View memories through physical contact.",
  "Future Sight": "See brief glimpses of possible futures.",
  "Spirit Sight": "See souls, ghosts, and hidden presences.",
  "X-Ray Vision": "See through solid objects and barriers.",
  "Enhanced Senses": "See, hear, and smell beyond human limits.",
  "Danger Sense": "Feel an instinctive warning before danger strikes.",
  "Perfect Aim": "Strike any target within your physical reach.",
  Genius: "Learn, calculate, and invent at extraordinary speed.",
  "Machine Command": "Control machines through direct contact.",
  "Animal Speech": "Understand and speak with animals.",
  "Plant Growth": "Cause plants to grow at impossible speed.",
  "Monster Taming": "Calm and befriend dangerous creatures.",
  "Power Copying": "Temporarily imitate a gift you witness.",
  "Power Nullification": "Suppress another gift while you remain close.",
  "Energy Absorption": "Absorb incoming energy to empower yourself.",
  "Kinetic Storage": "Store physical impacts and release their force.",
  "Damage Reflection": "Return a portion of received harm to its source.",
  Luck: "Tilt small chances subtly in your favor.",
  "Dream Walking": "Enter and explore the dreams of others.",
  "Astral Projection": "Send your spirit beyond your sleeping body.",
  "Curse Casting": "Place lingering supernatural misfortune on a target.",
  Barriers: "Raise durable walls of invisible energy.",
  Threads: "Create and command unnaturally strong threads.",
  Paper: "Shape paper into moving tools and weapons.",
  Ink: "Bring drawings and written marks briefly to life.",
  "Time Stop": "Freeze time around you for a few moments.",
  Custom: "A singular gift shaped entirely by you.",
} satisfies Record<Gift, string>;
